- name: create simone user
  tags: always
  user:
    name: simone
    group: root

- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFSUZoV7DiPxErsMwBRwK5vYTSGf3oEHrD+vrgegYTkf ansible

- name: add sudoers file for simone
  tags: always
  copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
